apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "%s-%s" .Release.Name .Release.Namespace }}
  labels:
    {{- include "hetzner-pvc.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ default "ReadWriteOnce" .Values.accessMode }}
  capacity:
    storage: {{ default "10Gi" .Values.size }}
  csi:
    volumeHandle: "{{ .Values.volumeHandle }}"
    driver: csi.hetzner.cloud
    fsType: {{ default "ext4" .Values.fsType }}
  storageClassName: {{ default "hcloud-volumes" .Values.storageClass }}
