{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openvscode-server.fullname" . }}
  labels:
    {{- include "openvscode-server.selectorLabels" . | nindent 4 }}
spec:
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.service.port }}
  selector:
    {{- include "openvscode-server.selectorLabels" . | nindent 4 }}
{{- end }}