apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-%s" .Release.Namespace .Release.Name }}
  labels:
    {{- include "nfs-pvc.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ default "ReadWriteMany" .Values.accessMode }}
  storageClassName: {{ default "nfs" .Values.storageClass }}
  resources:
    requests:
      storage: {{ default "10Gi" .Values.size }}
  volumeName: {{ printf "%s-%s" .Release.Name .Release.Namespace }}
