apiVersion: v2
name: hetzner-pvc
description: Hetzner PVCs for kubernetes
type: application
version: 1.0.0
appVersion: 1.0.0
maintainers:
  - name: Nazar Kulyk
    email: spam@myeburg.net
keywords:
  - services
  - persistance
